---
kind: pipeline
name: moss-work

steps:
  - name: render
    image: mosstech/drone-gke-deployer:latest
    commands:
      - ./go render
    when:
      event: push
      branch: master

  - name: build  
    image: mosstech/gcloud-and-docker:latest
    environment:
      GCP_PROJECT_ID:
        from_secret: MW_PROJECT_ID
      K8S_DEPLOYER_CREDS:
        from_secret: MW_K8S_DEPLOYER
    commands:
      - ./go build
    when:
      event: push
      branch: master

  - name: deploy
    image: mosstech/drone-gke-deployer:latest
    environment:
      GCP_PROJECT_ID:
        from_secret: MW_PROJECT_ID
      K8S_DEPLOYER_CREDS:
        from_secret: MW_K8S_DEPLOYER
      K8S_CLUSTER_NAME:
        from_secret: MW_K8S_CLUSTER_NAME
    commands:
      - ./go deploy
    when:
      event: push
      branch: master
