---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: moss-work-tls
spec:
  acme:
    config:
      - dns01:
          provider: prod-dns
        domains:
          - moss.work
          - www.moss.work
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: moss-work-tls
  commonName: moss.work
  dnsNames:
    - moss.work
    - www.moss.work
