---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moss-work
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: moss-work
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      containers:
      - name: moss-work
        image: moss-work:SET_BY_CI
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 250Mi
        ports:
        - name: http
          containerPort: 8080
        - name: metrics
          containerPort: 9145
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
        volumeMounts:
          - mountPath: /var/cache/nginx/data
            name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir: {}
