---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moss-work
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: moss-work
  template:
    metadata:
      labels:
        app: moss-work
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - moss-work
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: moss-work
          image: moss-work:SET_BY_CI
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 250Mi
          ports:
            - containerPort: 80
