---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ing-moss-work
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: moss-work-tls
      hosts:
        - moss.work
        - www.moss.work
  rules:
    - host: moss.work
      http:
        paths:
          - path: /
            backend:
              serviceName: moss-work-svc
              servicePort: 80
    - host: www.moss.work
      http:
        paths:
          - path: /
            backend:
              serviceName: moss-work-svc
              servicePort: 80
