---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: moss-work
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: moss-work-tls
      hosts:
        - moss.work
        - www.moss.work
  rules:
    - host: moss.work
      http:
        paths:
          - path: /
            backend:
              serviceName: moss-work
              servicePort: http
    - host: www.moss.work
      http:
        paths:
          - path: /
            backend:
              serviceName: moss-work
              servicePort: http
