apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moss-work

commonLabels:
  app: moss-work

resources:
  - deployment.yaml
  - ingress.yaml
  - pdb.yaml
  - service.yaml
  - servicemonitor.yaml
