---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: moss-work
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: moss-work
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: moss-work-istio
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: moss-work
  endpoints:
  - interval: 30s
    path: /stats/prometheus
    port: istio-proxy
