---
apiVersion: v1
kind: Service
metadata:
  name: moss-work
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: moss-work-metrics
spec:
  type: NodePort
  ports:
    - port: 9145
      name: metrics
