---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alexmoss
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: alexmoss
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
