---
apiVersion: v1
kind: Service
metadata:
  name: alexmoss-co-uk
spec:
  type: NodePort
  ports:
    - port: 32080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: alexmoss-co-uk-metrics
spec:
  type: NodePort
  selector:
    app: alexmoss-co-uk
  ports:
    - port: 9145
      name: metrics
